import { SPECIES } from 'models/SpriteSpecies/constants';

export const COAT_VARIANTS = Object.freeze({
  ALBINO: 1,
  CALICO: 2,
  DAWNISH: 3,
  EARTHEN: 4,
  LUARIAN: 5,
  MELANISTIC: 6,
  PIEBALD: 7,
  SAYLIAN: 8,
});

export const COATS = Object.freeze({
  ARKO_ALBINO: [SPECIES.ARKO, COAT_VARIANTS.ALBINO],
  ARKO_MELANISTIC: [SPECIES.ARKO, COAT_VARIANTS.MELANISTIC],
  ARKO_PIEBALD: [SPECIES.ARKO, COAT_VARIANTS.PIEBALD],
  ARKO_LUARIAN: [SPECIES.ARKO, COAT_VARIANTS.LUARIAN],
  ARKO_SAYLIAN: [SPECIES.ARKO, COAT_VARIANTS.SAYLIAN],
  ARKO_EARTHEN: [SPECIES.ARKO, COAT_VARIANTS.EARTHEN],

  NIBIAN_ALBINO: [SPECIES.NIBIAN, COAT_VARIANTS.ALBINO],
  NIBIAN_MELANISTIC: [SPECIES.NIBIAN, COAT_VARIANTS.MELANISTIC],
  NIBIAN_PIEBALD: [SPECIES.NIBIAN, COAT_VARIANTS.PIEBALD],
  NIBIAN_LUARIAN: [SPECIES.NIBIAN, COAT_VARIANTS.LUARIAN],
  NIBIAN_SAYLIAN: [SPECIES.NIBIAN, COAT_VARIANTS.SAYLIAN],

  CHIRLING_ALBINO: [SPECIES.CHIRLING, COAT_VARIANTS.ALBINO],
  CHIRLING_MELANISTIC: [SPECIES.CHIRLING, COAT_VARIANTS.MELANISTIC],
  CHIRLING_PIEBALD: [SPECIES.CHIRLING, COAT_VARIANTS.PIEBALD],
  CHIRLING_LUARIAN: [SPECIES.CHIRLING, COAT_VARIANTS.LUARIAN],
  CHIRLING_SAYLIAN: [SPECIES.CHIRLING, COAT_VARIANTS.SAYLIAN],

  GAM_ALBINO: [SPECIES.GAM, COAT_VARIANTS.ALBINO],
  GAM_MELANISTIC: [SPECIES.GAM, COAT_VARIANTS.MELANISTIC],
  GAM_PIEBALD: [SPECIES.GAM, COAT_VARIANTS.PIEBALD],
  GAM_LUARIAN: [SPECIES.GAM, COAT_VARIANTS.LUARIAN],
  GAM_SAYLIAN: [SPECIES.GAM, COAT_VARIANTS.SAYLIAN],

  SENRIX_ALBINO: [SPECIES.SENRIX, COAT_VARIANTS.ALBINO],
  SENRIX_MELANISTIC: [SPECIES.SENRIX, COAT_VARIANTS.MELANISTIC],
  SENRIX_PIEBALD: [SPECIES.SENRIX, COAT_VARIANTS.PIEBALD],
  SENRIX_LUARIAN: [SPECIES.SENRIX, COAT_VARIANTS.LUARIAN],
  SENRIX_SAYLIAN: [SPECIES.SENRIX, COAT_VARIANTS.SAYLIAN],
  SENRIX_EARTHEN: [SPECIES.SENRIX, COAT_VARIANTS.EARTHEN],

  VELA_ALBINO: [SPECIES.VELA, COAT_VARIANTS.ALBINO],
  VELA_MELANISTIC: [SPECIES.VELA, COAT_VARIANTS.MELANISTIC],
  VELA_PIEBALD: [SPECIES.VELA, COAT_VARIANTS.PIEBALD],
  VELA_LUARIAN: [SPECIES.VELA, COAT_VARIANTS.LUARIAN],
  VELA_SAYLIAN: [SPECIES.VELA, COAT_VARIANTS.SAYLIAN],
  VELA_DAWNISH: [SPECIES.VELA, COAT_VARIANTS.DAWNISH],

  FLEURAN_ALBINO: [SPECIES.FLEURAN, COAT_VARIANTS.ALBINO],
  FLEURAN_MELANISTIC: [SPECIES.FLEURAN, COAT_VARIANTS.MELANISTIC],
  FLEURAN_PIEBALD: [SPECIES.FLEURAN, COAT_VARIANTS.PIEBALD],
  FLEURAN_LUARIAN: [SPECIES.FLEURAN, COAT_VARIANTS.LUARIAN],
  FLEURAN_SAYLIAN: [SPECIES.FLEURAN, COAT_VARIANTS.SAYLIAN],
  FLEURAN_CALICO: [SPECIES.FLEURAN, COAT_VARIANTS.CALICO],

  EYDRUN_ALBINO: [SPECIES.EYDRUN, COAT_VARIANTS.ALBINO],
  EYDRUN_MELANISTIC: [SPECIES.EYDRUN, COAT_VARIANTS.MELANISTIC],
  EYDRUN_PIEBALD: [SPECIES.EYDRUN, COAT_VARIANTS.PIEBALD],
  EYDRUN_LUARIAN: [SPECIES.EYDRUN, COAT_VARIANTS.LUARIAN],
  EYDRUN_SAYLIAN: [SPECIES.EYDRUN, COAT_VARIANTS.SAYLIAN],

  GORBIN_ALBINO: [SPECIES.GORBIN, COAT_VARIANTS.ALBINO],
  GORBIN_MELANISTIC: [SPECIES.GORBIN, COAT_VARIANTS.MELANISTIC],
  GORBIN_PIEBALD: [SPECIES.GORBIN, COAT_VARIANTS.PIEBALD],
  GORBIN_LUARIAN: [SPECIES.GORBIN, COAT_VARIANTS.LUARIAN],
  GORBIN_SAYLIAN: [SPECIES.GORBIN, COAT_VARIANTS.SAYLIAN],

  LOXI_ALBINO: [SPECIES.LOXI, COAT_VARIANTS.ALBINO],
  LOXI_MELANISTIC: [SPECIES.LOXI, COAT_VARIANTS.MELANISTIC],
  LOXI_PIEBALD: [SPECIES.LOXI, COAT_VARIANTS.PIEBALD],
  LOXI_LUARIAN: [SPECIES.LOXI, COAT_VARIANTS.LUARIAN],
  LOXI_SAYLIAN: [SPECIES.LOXI, COAT_VARIANTS.SAYLIAN],
});
